// <auto-generated />
using System;
using CineCoreBack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CineCoreBack.Migrations
{
    [DbContext(typeof(DbConfig))]
    [Migration("20260429021748_ImplementDatabaseOptimizations")]
    partial class ImplementDatabaseOptimizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_acquisition_type", new[] { "buy", "rent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_cast_status", new[] { "pending", "approved", "hold", "declined" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_gender", new[] { "f", "m", "any" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_location_type", new[] { "interior", "exterior", "studio" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_member_status", new[] { "pending", "active", "declined" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_prop_status", new[] { "available", "leased", "unavailable" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_prop_type", new[] { "action", "scenography", "functional" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_resource_type", new[] { "ROLE", "LOCATION", "PROP" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_role_type", new[] { "lead", "supporting", "extra" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_scene_status", new[] { "draft", "complete" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_script_element", new[] { "action", "character", "dialogue", "parenthetical", "transition", "shot" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_shoot_day_status", new[] { "draft", "generated", "published", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enm_system_role", new[] { "owner", "manager", "actor" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CineCoreBack.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Characteristics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("characteristics")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id")
                        .HasName("actors_pkey");

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.CallSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PublishedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("published_by_user_id");

                    b.Property<int>("ShootDayId")
                        .HasColumnType("integer")
                        .HasColumnName("shoot_day_id");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_data");

                    b.Property<int>("VersionNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version_num");

                    b.HasKey("Id")
                        .HasName("call_sheets_pkey");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex(new[] { "ShootDayId", "VersionNum" }, "unq_shoot_day_version")
                        .IsUnique();

                    b.ToTable("call_sheets", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.Casting", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<DateOnly>("CastDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("cast_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("CastStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("cast_status")
                        .HasDefaultValueSql("'pending'::enm_cast_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("RoleId", "ActorId")
                        .HasName("casting_pkey");

                    b.HasIndex("ActorId");

                    b.ToTable("casting", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("genres_pkey");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location_name");

                    b.Property<string>("LocationType")
                        .HasColumnType("text")
                        .HasColumnName("location_type");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("locations_pkey");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Synopsis")
                        .HasColumnType("text")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("projects_pkey");

                    b.HasIndex(new[] { "OwnerId", "Title" }, "uq_projects_owner_title")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.ProjectGenre", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("ProjectId", "GenreId")
                        .HasName("project_genres_pkey");

                    b.HasIndex("GenreId");

                    b.ToTable("project_genres", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.ProjectInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_sent")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int>("InvitedById")
                        .HasColumnType("integer")
                        .HasColumnName("invited_by_id");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("SysRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sys_role");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("project_invitations_pkey");

                    b.HasIndex("InvitedById");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_invitations", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.ProjectMember", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("invited_email");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department");

                    b.Property<DateTime?>("InvitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("InvitedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("SysRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("manager")
                        .HasColumnName("sys_role");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ProjectId", "InvitedEmail")
                        .HasName("project_members_pkey");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.Prop", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("AcquisitionType")
                        .HasColumnType("text")
                        .HasColumnName("acquisition_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("prop_name");

                    b.Property<string>("PropStatus")
                        .HasColumnType("text")
                        .HasColumnName("prop_status");

                    b.Property<string>("PropType")
                        .HasColumnType("text")
                        .HasColumnName("prop_type");

                    b.HasKey("Id")
                        .HasName("props_pkey");

                    b.ToTable("props", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("resources_pkey");

                    b.HasIndex("ProjectId");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<string>("Characteristics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("characteristics")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex")
                        .HasDefaultValueSql("'#333333'::character varying");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsAutoGenerated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_auto_generated");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("role_name");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("role_type")
                        .HasDefaultValueSql("'supporting'::enm_role_type");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex("ProjectId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("EstimatedDuration")
                        .HasColumnType("interval")
                        .HasColumnName("estimated_duration");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("SequenceNum")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_num");

                    b.Property<string>("SluglineText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slugline_text");

                    b.HasKey("Id")
                        .HasName("scenes_pkey");

                    b.HasIndex(new[] { "ProjectId", "SequenceNum" }, "uq_project_scene_num")
                        .IsUnique();

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.SceneResource", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("integer")
                        .HasColumnName("scene_id");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("SceneId", "ResourceId")
                        .HasName("scene_resource_pkey");

                    b.HasIndex("ResourceId");

                    b.ToTable("scene_resource", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.SceneSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("PrepTimeEstimate")
                        .HasColumnType("interval")
                        .HasColumnName("prep_time_estimate");

                    b.Property<int>("SceneId")
                        .HasColumnType("integer")
                        .HasColumnName("scene_id");

                    b.Property<int>("SceneOrder")
                        .HasColumnType("integer")
                        .HasColumnName("scene_order");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<int>("ShootDayId")
                        .HasColumnType("integer")
                        .HasColumnName("shoot_day_id");

                    b.Property<TimeSpan?>("ShootTimeEstimate")
                        .HasColumnType("interval")
                        .HasColumnName("shoot_time_estimate");

                    b.HasKey("Id")
                        .HasName("scene_schedule_pkey");

                    b.HasIndex("SceneId");

                    b.HasIndex(new[] { "ShootDayId", "SceneId" }, "unq_scene_in_day")
                        .IsUnique();

                    b.ToTable("scene_schedule", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.ScriptElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element_type");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("SceneId")
                        .HasColumnType("integer")
                        .HasColumnName("scene_id");

                    b.HasKey("Id")
                        .HasName("script_elements_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "SceneId", "OrderIndex" }, "uq_scene_element_order")
                        .IsUnique();

                    b.ToTable("script_elements", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.ShootDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("base_location_id");

                    b.Property<string>("GeneralNotes")
                        .HasColumnType("text")
                        .HasColumnName("general_notes");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shift_end");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shift_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enm_shoot_day_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'draft'::enm_shoot_day_status");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unit_name")
                        .HasDefaultValueSql("'Main Unit'::character varying");

                    b.HasKey("Id")
                        .HasName("shoot_days_pkey");

                    b.HasIndex("BaseLocationId");

                    b.HasIndex(new[] { "ProjectId", "UnitName", "ShiftStart" }, "unq_project_unit_shift")
                        .IsUnique();

                    b.ToTable("shoot_days", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarTheme")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("avatar_theme")
                        .HasDefaultValueSql("'theme-teal'::character varying");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNum")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_num");

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CineCoreBack.Models.Actor", b =>
                {
                    b.HasOne("CineCoreBack.Models.User", "User")
                        .WithOne("Actor")
                        .HasForeignKey("CineCoreBack.Models.Actor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("actors_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CineCoreBack.Models.CallSheet", b =>
                {
                    b.HasOne("CineCoreBack.Models.User", "PublishedByUser")
                        .WithMany("CallSheets")
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("call_sheets_published_by_user_id_fkey");

                    b.HasOne("CineCoreBack.Models.ShootDay", "ShootDay")
                        .WithMany("CallSheets")
                        .HasForeignKey("ShootDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("call_sheets_shoot_day_id_fkey");

                    b.Navigation("PublishedByUser");

                    b.Navigation("ShootDay");
                });

            modelBuilder.Entity("CineCoreBack.Models.Casting", b =>
                {
                    b.HasOne("CineCoreBack.Models.Actor", "Actor")
                        .WithMany("Castings")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("casting_actor_id_fkey");

                    b.HasOne("CineCoreBack.Models.Role", "Role")
                        .WithMany("Castings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("casting_role_id_fkey");

                    b.Navigation("Actor");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CineCoreBack.Models.Location", b =>
                {
                    b.HasOne("CineCoreBack.Models.Resource", "IdNavigation")
                        .WithOne("Location")
                        .HasForeignKey("CineCoreBack.Models.Location", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("locations_id_fkey");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("CineCoreBack.Models.Project", b =>
                {
                    b.HasOne("CineCoreBack.Models.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("projects_owner_id_fkey");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CineCoreBack.Models.ProjectGenre", b =>
                {
                    b.HasOne("CineCoreBack.Models.Genre", "Genre")
                        .WithMany("ProjectGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_genres_genre_id_fkey");

                    b.HasOne("CineCoreBack.Models.Project", "Project")
                        .WithMany("ProjectGenres")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_genres_project_id_fkey");

                    b.Navigation("Genre");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CineCoreBack.Models.ProjectInvitation", b =>
                {
                    b.HasOne("CineCoreBack.Models.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_invitations_invited_by_id_fkey");

                    b.HasOne("CineCoreBack.Models.Project", "Project")
                        .WithMany("ProjectInvitations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_invitations_project_id_fkey");

                    b.Navigation("InvitedBy");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CineCoreBack.Models.ProjectMember", b =>
                {
                    b.HasOne("CineCoreBack.Models.User", "InvitedByUser")
                        .WithMany("ProjectMemberInvitedByUsers")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("project_members_invited_by_user_id_fkey");

                    b.HasOne("CineCoreBack.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("project_members_project_id_fkey");

                    b.HasOne("CineCoreBack.Models.User", "User")
                        .WithMany("ProjectMemberUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("project_members_user_id_fkey");

                    b.Navigation("InvitedByUser");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CineCoreBack.Models.Prop", b =>
                {
                    b.HasOne("CineCoreBack.Models.Resource", "IdNavigation")
                        .WithOne("Prop")
                        .HasForeignKey("CineCoreBack.Models.Prop", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("props_id_fkey");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("CineCoreBack.Models.Resource", b =>
                {
                    b.HasOne("CineCoreBack.Models.Project", "Project")
                        .WithMany("Resources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("resources_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CineCoreBack.Models.Role", b =>
                {
                    b.HasOne("CineCoreBack.Models.Resource", "IdNavigation")
                        .WithOne("Role")
                        .HasForeignKey("CineCoreBack.Models.Role", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("roles_id_fkey");

                    b.HasOne("CineCoreBack.Models.Project", "Project")
                        .WithMany("Roles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("roles_project_id_fkey");

                    b.Navigation("IdNavigation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CineCoreBack.Models.Scene", b =>
                {
                    b.HasOne("CineCoreBack.Models.Project", "Project")
                        .WithMany("Scenes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("scenes_project_id_fkey");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CineCoreBack.Models.SceneResource", b =>
                {
                    b.HasOne("CineCoreBack.Models.Resource", "Resource")
                        .WithMany("SceneResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("scene_resource_resource_id_fkey");

                    b.HasOne("CineCoreBack.Models.Scene", "Scene")
                        .WithMany("SceneResources")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("scene_resource_scene_id_fkey");

                    b.Navigation("Resource");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("CineCoreBack.Models.SceneSchedule", b =>
                {
                    b.HasOne("CineCoreBack.Models.Scene", "Scene")
                        .WithMany("SceneSchedules")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("scene_schedule_scene_id_fkey");

                    b.HasOne("CineCoreBack.Models.ShootDay", "ShootDay")
                        .WithMany("SceneSchedules")
                        .HasForeignKey("ShootDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("scene_schedule_shoot_day_id_fkey");

                    b.Navigation("Scene");

                    b.Navigation("ShootDay");
                });

            modelBuilder.Entity("CineCoreBack.Models.ScriptElement", b =>
                {
                    b.HasOne("CineCoreBack.Models.Role", "Role")
                        .WithMany("ScriptElements")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("script_elements_role_id_fkey");

                    b.HasOne("CineCoreBack.Models.Scene", "Scene")
                        .WithMany("ScriptElements")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("script_elements_scene_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("CineCoreBack.Models.ShootDay", b =>
                {
                    b.HasOne("CineCoreBack.Models.Location", "BaseLocation")
                        .WithMany("ShootDays")
                        .HasForeignKey("BaseLocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("shoot_days_base_location_id_fkey");

                    b.HasOne("CineCoreBack.Models.Project", "Project")
                        .WithMany("ShootDays")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shoot_days_project_id_fkey");

                    b.Navigation("BaseLocation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CineCoreBack.Models.Actor", b =>
                {
                    b.Navigation("Castings");
                });

            modelBuilder.Entity("CineCoreBack.Models.Genre", b =>
                {
                    b.Navigation("ProjectGenres");
                });

            modelBuilder.Entity("CineCoreBack.Models.Location", b =>
                {
                    b.Navigation("ShootDays");
                });

            modelBuilder.Entity("CineCoreBack.Models.Project", b =>
                {
                    b.Navigation("ProjectGenres");

                    b.Navigation("ProjectInvitations");

                    b.Navigation("ProjectMembers");

                    b.Navigation("Resources");

                    b.Navigation("Roles");

                    b.Navigation("Scenes");

                    b.Navigation("ShootDays");
                });

            modelBuilder.Entity("CineCoreBack.Models.Resource", b =>
                {
                    b.Navigation("Location");

                    b.Navigation("Prop");

                    b.Navigation("Role");

                    b.Navigation("SceneResources");
                });

            modelBuilder.Entity("CineCoreBack.Models.Role", b =>
                {
                    b.Navigation("Castings");

                    b.Navigation("ScriptElements");
                });

            modelBuilder.Entity("CineCoreBack.Models.Scene", b =>
                {
                    b.Navigation("SceneResources");

                    b.Navigation("SceneSchedules");

                    b.Navigation("ScriptElements");
                });

            modelBuilder.Entity("CineCoreBack.Models.ShootDay", b =>
                {
                    b.Navigation("CallSheets");

                    b.Navigation("SceneSchedules");
                });

            modelBuilder.Entity("CineCoreBack.Models.User", b =>
                {
                    b.Navigation("Actor");

                    b.Navigation("CallSheets");

                    b.Navigation("ProjectMemberInvitedByUsers");

                    b.Navigation("ProjectMemberUsers");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
