using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CineCoreBack.Models;
using CineCoreBack.DTOs;

namespace CineCoreBack.Controllers;

[Route("api")]
[ApiController]
public class CastingController : ControllerBase
{
    private readonly DbConfig _context;

    public CastingController(DbConfig context)
    {
        _context = context;
    }

    // ==========================================
    // 1. УПРАВЛІННЯ РОЛЯМИ В ПРОЕКТІ (Для Менеджера)
    // ==========================================

    [HttpGet("projects/{projectId}/roles")]
    public async Task<ActionResult<IEnumerable<RoleDto>>> GetRoles(int projectId)
    {
        var roles = await _context.Roles
            .Where(r => r.ProjectId == projectId)
            .Include(r => r.Castings)
            .Select(r => new RoleDto
            {
                Id = r.Id,
                RoleName = r.RoleName,
                Description = r.Description,
                Age = r.Age,
                Characteristics = r.Characteristics,
                RoleType = r.RoleType,
                ColorHex = r.ColorHex,
                CandidatesCount = r.Castings.Count
            })
            .ToListAsync();

        return Ok(roles);
    }

    [HttpPost("projects/{projectId}/roles")]
    public async Task<ActionResult<RoleDto>> CreateRole(int projectId, CreateRoleDto dto)
    {
        var resource = new Resource { ProjectId = projectId };
        _context.Resources.Add(resource);
        await _context.SaveChangesAsync(); // Генеруємо ID ресурсу

        var role = new Role
        {
            Id = resource.Id, // Використовуємо ID ресурсу
            ProjectId = projectId,
            RoleName = dto.RoleName,
            Description = dto.Description,
            Age = dto.Age,
            Characteristics = dto.Characteristics ?? "{}",
            RoleType = dto.RoleType,
            ColorHex = dto.ColorHex ?? "#51A2FF",
            IsAutoGenerated = false
        };

        _context.Roles.Add(role);
        await _context.SaveChangesAsync();

        return Ok(new { message = "Role created successfully", roleId = role.Id });
    }

    [HttpPut("projects/{projectId}/roles/{roleId}")]
    public async Task<IActionResult> UpdateRole(int projectId, int roleId, UpdateRoleDto dto)
    {
        var role = await _context.Roles.FirstOrDefaultAsync(r => r.Id == roleId && r.ProjectId == projectId);
        if (role == null) return NotFound("Role not found");

        role.RoleName = dto.RoleName;
        role.Description = dto.Description;
        role.Age = dto.Age;
        role.Characteristics = dto.Characteristics;
        role.RoleType = dto.RoleType;
        if (dto.ColorHex != null) role.ColorHex = dto.ColorHex;

        await _context.SaveChangesAsync();
        return Ok(new { message = "Role updated successfully" });
    }

    [HttpDelete("projects/{projectId}/roles/{roleId}")]
    public async Task<IActionResult> DeleteRole(int projectId, int roleId)
    {
        var role = await _context.Roles.FirstOrDefaultAsync(r => r.Id == roleId && r.ProjectId == projectId);
        if (role == null) return NotFound();

        var resource = await _context.Resources.FindAsync(roleId);

        _context.Roles.Remove(role);
        if (resource != null) _context.Resources.Remove(resource);

        await _context.SaveChangesAsync();
        return Ok(new { message = "Role deleted successfully" });
    }

    // ==========================================
    // 2. УПРАВЛІННЯ КАНДИДАТАМИ (Для Менеджера)
    // ==========================================

    [HttpGet("projects/{projectId}/roles/{roleId}/candidates")]
    public async Task<ActionResult<IEnumerable<CandidateDto>>> GetCandidates(int projectId, int roleId)
    {
        var candidates = await _context.Castings
            .Where(c => c.RoleId == roleId)
            .Include(c => c.Actor)          // Підключаємо профіль актора
                .ThenInclude(a => a.User)   // Підключаємо користувача (для імені, пошти)
            .Select(c => new CandidateDto
            {
                ActorId = c.ActorId,
                FirstName = c.Actor.User.FirstName,
                LastName = c.Actor.User.LastName,
                Email = c.Actor.User.Email,
                PhoneNum = c.Actor.User.PhoneNum,
                AvatarTheme = c.Actor.User.AvatarTheme,
                Characteristics = c.Actor.Characteristics,
                CastStatus = c.CastStatus,
                CastDate = c.CastDate,
                Notes = c.Notes
            })
            .ToListAsync();

        return Ok(candidates);
    }

    [HttpPost("projects/{projectId}/roles/{roleId}/candidates")]
    public async Task<IActionResult> AddCandidate(int projectId, int roleId, AddCandidateDto dto)
    {
        // 1. Перевіряємо, чи існує такий юзер. Якщо так, чи є він актором? Якщо ні - створюємо запис в Actor
        var userExists = await _context.Users.AnyAsync(u => u.Id == dto.ActorId);
        if (!userExists) return NotFound("User not found");

        var actorExists = await _context.Actors.AnyAsync(a => a.Id == dto.ActorId);
        if (!actorExists)
        {
            _context.Actors.Add(new Actor { Id = dto.ActorId, Characteristics = "{}" });
            await _context.SaveChangesAsync();
        }

        // 2. Перевіряємо, чи він вже не є кандидатом
        var alreadyCasting = await _context.Castings.AnyAsync(c => c.RoleId == roleId && c.ActorId == dto.ActorId);
        if (alreadyCasting) return BadRequest("Actor is already a candidate for this role.");

        var casting = new Casting
        {
            RoleId = roleId,
            ActorId = dto.ActorId,
            CastDate = DateOnly.FromDateTime(DateTime.UtcNow),
            CastStatus = "pending",
            Notes = dto.Notes
        };

        _context.Castings.Add(casting);
        await _context.SaveChangesAsync();

        return Ok(new { message = "Candidate added successfully" });
    }

    [HttpPut("projects/{projectId}/roles/{roleId}/candidates/{actorId}/status")]
    public async Task<IActionResult> UpdateCandidateStatus(int projectId, int roleId, int actorId, UpdateCastStatusDto dto)
    {
        var casting = await _context.Castings.FirstOrDefaultAsync(c => c.RoleId == roleId && c.ActorId == actorId);
        if (casting == null) return NotFound("Candidate not found");

        casting.CastStatus = dto.CastStatus;
        await _context.SaveChangesAsync();

        return Ok(new { message = "Status updated successfully", newStatus = casting.CastStatus });
    }

    // ==========================================
    // 3. ОСОБИСТИЙ ПРОФІЛЬ (Для Актора)
    // ==========================================

    [HttpGet("actors/{userId}/profile")]
    public async Task<ActionResult<ActorProfileDto>> GetActorProfile(int userId)
    {
        // В реальному проекті тут варто перевіряти JWT токен, чи користувач запитує свій профіль

        var user = await _context.Users
            .Include(u => u.Actor) // Actor може бути null, якщо ще не створений
            .FirstOrDefaultAsync(u => u.Id == userId);

        if (user == null) return NotFound("User not found");

        var profile = new ActorProfileDto
        {
            Id = user.Id,
            FirstName = user.FirstName,
            LastName = user.LastName,
            Email = user.Email,
            PhoneNum = user.PhoneNum,
            Birthday = user.Birthday.HasValue ? DateOnly.FromDateTime(user.Birthday.Value) : null,
            AvatarTheme = user.AvatarTheme,
            Characteristics = user.Actor?.Characteristics ?? "{}"
        };

        return Ok(profile);
    }

    [HttpPut("actors/{userId}/characteristics")]
    public async Task<IActionResult> UpdateActorCharacteristics(int userId, UpdateActorCharacteristicsDto dto)
    {
        var actor = await _context.Actors.FindAsync(userId);

        if (actor == null)
        {
            // Якщо профілю актора ще немає, створюємо його
            actor = new Actor { Id = userId, Characteristics = dto.Characteristics };
            _context.Actors.Add(actor);
        }
        else
        {
            actor.Characteristics = dto.Characteristics;
        }

        await _context.SaveChangesAsync();
        return Ok(new { message = "Characteristics updated successfully" });
    }
}