using CineCoreBack.DTOs;
using CineCoreBack.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace CineCoreBack.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ScriptController : ControllerBase
    {
        private readonly DbConfig _context;

        public ScriptController(DbConfig context)
        {
            _context = context;
        }

        // 1. АВТОМАТИЧНЕ ЗБЕРЕЖЕННЯ ТА СИНХРОНІЗАЦІЯ (З підтримкою Auto-Split)
        [HttpPost("scene/{sceneId}/autosave")]
        public async Task<IActionResult> AutoSaveScript(int sceneId, [FromBody] ScriptSaveDto dto)
        {
            var scene = await _context.Scenes.FindAsync(sceneId);
            if (scene == null) return NotFound();

            // ==========================================
            // КРОК А: Робота з персонажами (Існуючий функціонал)
            // ==========================================
            var existingRoles = await _context.Roles
                .Where(r => r.ProjectId == dto.ProjectId)
                .ToListAsync();

            var characterBlocks = dto.Blocks
                .Where(b => b.Type.ToLower() == "character")
                .Select(b => b.Content.Trim().ToUpper())
                .Distinct()
                .ToList();

            foreach (var name in characterBlocks)
            {
                var existing = existingRoles.FirstOrDefault(r => r.RoleName.ToUpper() == name);
                if (existing == null)
                {
                    var res = new Resource { ProjectId = dto.ProjectId };
                    _context.Resources.Add(res);
                    await _context.SaveChangesAsync();

                    var newRole = new Role
                    {
                        Id = res.Id,
                        ProjectId = dto.ProjectId,
                        RoleName = name,
                        IsAutoGenerated = true, // Новий персонаж завжди Auto
                        ColorHex = "#3AB9A0"
                    };
                    _context.Roles.Add(newRole);
                    existingRoles.Add(newRole);
                }
            }
            await _context.SaveChangesAsync();

            // ==========================================
            // КРОК Б: Логіка розділення сцен (Auto-Split)
            // ==========================================

            // 1. Рахуємо, скільки ДОДАТКОВИХ сцен нам треба створити
            int totalHeadings = dto.Blocks.Count(b => b.Type.ToLower() == "scene_heading");
            int extraScenesNeeded = totalHeadings > 1 ? totalHeadings - 1 : 0;

            // 2. Якщо є додаткові сцени, зсуваємо нумерацію (SequenceNum) всіх наступних сцен у проекті
            if (extraScenesNeeded > 0)
            {
                var trailingScenes = await _context.Scenes
                    .Where(s => s.ProjectId == dto.ProjectId && s.SequenceNum > scene.SequenceNum)
                    .ToListAsync();

                foreach (var s in trailingScenes)
                {
                    s.SequenceNum += extraScenesNeeded;
                }
                await _context.SaveChangesAsync();
            }

            // 3. Wipe & Replace (Очищення старих елементів ТІЛЬКИ для поточної сцени)
            var oldElements = _context.ScriptElements.Where(e => e.SceneId == sceneId);
            _context.ScriptElements.RemoveRange(oldElements);

            // ==========================================
            // КРОК В: Запис нових блоків і створення сцен
            // ==========================================
            Scene currentTargetScene = scene; // ОГОЛОШУЄМО ЗМІННУ ТУТ! Початково вказує на стару сцену.
            int order = 0;
            int? currentRoleId = null;
            bool isFirstHeading = true;
            int newScenesCreated = 0;

            // Словник для правильного розрахунку тривалості кожної сцени (старої і нових)
            var sceneBlocksMap = new Dictionary<Scene, List<ScriptBlockDto>>();
            sceneBlocksMap[currentTargetScene] = new List<ScriptBlockDto>();

            foreach (var block in dto.Blocks)
            {
                string type = block.Type.ToLower();

                if (type == "scene_heading")
                {
                    if (isFirstHeading)
                    {
                        currentTargetScene.SluglineText = block.Content;
                        sceneBlocksMap[currentTargetScene].Add(block); // Зберігаємо блок для розрахунку часу
                        isFirstHeading = false;
                    }
                    else
                    {
                        // ЗНАЙШЛИ НОВИЙ ЗАГОЛОВОК! Створюємо нову сцену
                        newScenesCreated++;
                        var newScene = new Scene
                        {
                            ProjectId = dto.ProjectId,
                            SequenceNum = scene.SequenceNum + newScenesCreated,
                            SluglineText = block.Content,
                            EstimatedDuration = TimeSpan.Zero
                        };
                        _context.Scenes.Add(newScene);
                        await _context.SaveChangesAsync(); // Зберігаємо, щоб отримати новий ID

                        currentTargetScene = newScene; // Перемикаємо "ціль" запису на нову сцену
                        sceneBlocksMap[currentTargetScene] = new List<ScriptBlockDto> { block };
                        order = 0; // Скидаємо порядок елементів для нової сцени
                        currentRoleId = null; // Скидаємо персонажа
                    }
                    continue; // Заголовок не зберігаємо як окремий ScriptElement у БД
                }

                // Записуємо елементи у поточну цільову сцену
                if (type == "character")
                {
                    currentRoleId = existingRoles.FirstOrDefault(r => r.RoleName.ToUpper() == block.Content.Trim().ToUpper())?.Id;
                }
                int? roleIdToSave = (type == "character" || type == "dialogue" || type == "parenthetical") ? currentRoleId : null;

                _context.ScriptElements.Add(new ScriptElement
                {
                    SceneId = currentTargetScene.Id, // Використовуємо ID поточної цілі
                    OrderIndex = order++,
                    Content = block.Content,
                    ElementType = type,
                    RoleId = roleIdToSave
                });

                sceneBlocksMap[currentTargetScene].Add(block); // Зберігаємо блок для розрахунку часу
            }

            await _context.SaveChangesAsync();


            // ==========================================
            // КРОК Д: Розрахунок тривалості сцен
            // ==========================================
            foreach (var kvp in sceneBlocksMap)
            {
                // Перераховуємо час тільки для тих блоків, які належать конкретній сцені
                kvp.Key.EstimatedDuration = EstimateSceneDuration(kvp.Value);
            }
            await _context.SaveChangesAsync();

            var duration = scene.EstimatedDuration.HasValue
                ? $"{(int)scene.EstimatedDuration.Value.TotalMinutes:D2}:{scene.EstimatedDuration.Value.Seconds:D2}"
                : null;

            return Ok(new { message = "Synced", estimatedDuration = duration, wasSplit = extraScenesNeeded > 0 });
        }

        // ОТРИМАННЯ СКРИПТУ ОДНІЄЇ СЦЕНИ (Відновлений метод)
        [HttpGet("scene/{sceneId}")]
        public async Task<IActionResult> GetScript(int sceneId)
        {
            var scene = await _context.Scenes
                .Include(s => s.ScriptElements).ThenInclude(e => e.Role)
                .FirstOrDefaultAsync(s => s.Id == sceneId);

            if (scene == null) return NotFound();

            var blocks = new List<object> {
                new { id = "h-" + scene.Id, type = "scene_heading", content = scene.SluglineText, sceneCode = "SC-" + scene.SequenceNum.ToString().PadLeft(3, '0') }
            };

            var elements = scene.ScriptElements.OrderBy(e => e.OrderIndex).Select(e => new {
                id = e.Id.ToString(),
                type = e.ElementType,
                content = e.Content,
                charId = e.RoleId?.ToString(),
                color = (e.ElementType == "character" || e.ElementType == "dialogue" || e.ElementType == "parenthetical") ? (e.Role?.ColorHex ?? "#444") : "#444"
            });
            blocks.AddRange(elements);

            // ДОДАНО: Витягуємо прикріплені ресурси сцени
            var sceneResources = await _context.SceneResources
                .Include(sr => sr.Resource.Role).Include(sr => sr.Resource.Location).Include(sr => sr.Resource.Prop)
                .Where(sr => sr.SceneId == sceneId).ToListAsync();

            var linkedRoles = sceneResources.Where(sr => sr.Resource.Role != null).Select(sr => new { id = sr.ResourceId, name = sr.Resource.Role.RoleName, color = sr.Resource.Role.ColorHex }).ToList();
            var linkedLocations = sceneResources.Where(sr => sr.Resource.Location != null).Select(sr => new { id = sr.ResourceId, name = sr.Resource.Location.LocationName, type = sr.Resource.Location.LocationType }).ToList();
            var linkedProps = sceneResources.Where(sr => sr.Resource.Prop != null).Select(sr => new { id = sr.ResourceId, name = sr.Resource.Prop.PropName }).ToList();

            return Ok(new { notes = scene.Notes, blocks = blocks, linkedRoles, linkedLocations, linkedProps });
        }

        // 1. ОТРИМАННЯ СПИСКУ СЦЕН (ДЛЯ ЛІВОЇ ПАНЕЛІ)
        [HttpGet("project/{projectId}/scenes")]
        public async Task<IActionResult> GetProjectScenes(int projectId)
        {
            var scenes = await _context.Scenes
                .Where(s => s.ProjectId == projectId)
                .OrderBy(s => s.SequenceNum)
                .Select(s => new {
                    id = s.Id,
                    sequenceNum = s.SequenceNum,
                    sluglineText = s.SluglineText,
                    estimatedDuration = s.EstimatedDuration
                })
                .ToListAsync();

            var result = scenes.Select(s => new {
                s.id,
                s.sequenceNum,
                s.sluglineText,
                // Формат "MM:SS" для UI; null якщо ще не розраховано
                estimatedDuration = s.estimatedDuration.HasValue
                    ? $"{(int)s.estimatedDuration.Value.TotalMinutes:D2}:{s.estimatedDuration.Value.Seconds:D2}"
                    : (string?)null
            });

            return Ok(result);
        }

        // ПЕРЕРАХУНОК ТРИВАЛОСТІ ВСІХ СЦЕН ПРОЕКТУ (одноразовий або при потребі)
        [HttpPost("project/{projectId}/recalculate-durations")]
        public async Task<IActionResult> RecalculateAllDurations(int projectId)
        {
            var scenes = await _context.Scenes
                .Include(s => s.ScriptElements)
                .Where(s => s.ProjectId == projectId)
                .ToListAsync();

            foreach (var scene in scenes)
            {
                // Конвертуємо ScriptElement назад у ScriptBlockDto для переліку
                // scene_heading додаємо окремо з SluglineText
                var blocks = new List<ScriptBlockDto>
                {
                    new ScriptBlockDto { Type = "scene_heading", Content = scene.SluglineText }
                };

                blocks.AddRange(scene.ScriptElements
                    .OrderBy(e => e.OrderIndex)
                    .Select(e => new ScriptBlockDto
                    {
                        Type = e.ElementType,
                        Content = e.Content
                    }));

                scene.EstimatedDuration = EstimateSceneDuration(blocks);
            }

            await _context.SaveChangesAsync();

            return Ok(new { updated = scenes.Count });
        }

        [HttpGet("project/{projectId}/full")]
        public async Task<IActionResult> GetFullScript(int projectId)
        {
            var scenes = await _context.Scenes
                .Include(s => s.ScriptElements).ThenInclude(e => e.Role)
                .Where(s => s.ProjectId == projectId)
                .OrderBy(s => s.SequenceNum)
                .ToListAsync();

            var result = new List<object>();

            foreach (var scene in scenes)
            {
                // Додаємо заголовок як блок
                result.Add(new
                {
                    id = "h-" + scene.Id,
                    type = "scene_heading",
                    content = scene.SluglineText,
                    sceneId = scene.Id,
                    sceneCode = "SC-" + scene.SequenceNum.ToString().PadLeft(3, '0')
                });

                // Додаємо елементи
                var elements = scene.ScriptElements.OrderBy(e => e.OrderIndex).Select(e => new {
                    id = e.Id.ToString(),
                    type = e.ElementType,
                    content = e.Content,
                    charId = e.RoleId,
                    color = (e.ElementType == "character" || e.ElementType == "dialogue" || e.ElementType == "parenthetical")
                        ? (e.Role?.ColorHex ?? "#444")
                        : "#444",
                    sceneId = scene.Id
                });
                result.AddRange(elements);
            }

            // Збираємо всі прикріплені ресурси для проекту (Для правої панелі у Full Script)
            var sceneResources = await _context.SceneResources
                .Include(sr => sr.Resource.Location)
                .Include(sr => sr.Resource.Prop)
                .Where(sr => sr.Scene.ProjectId == projectId)
                .ToListAsync();

            var linkedLocations = sceneResources
                .Where(sr => sr.Resource.Location != null)
                .Select(sr => new { id = sr.ResourceId, name = sr.Resource.Location.LocationName, type = sr.Resource.Location.LocationType })
                .DistinctBy(l => l.id) // Беремо тільки унікальні, щоб не дублювалися
                .ToList();

            var linkedProps = sceneResources
                .Where(sr => sr.Resource.Prop != null)
                .Select(sr => new { id = sr.ResourceId, name = sr.Resource.Prop.PropName })
                .DistinctBy(p => p.id) // Беремо тільки унікальні
                .ToList();

            return Ok(new
            {
                blocks = result,
                linkedLocations = linkedLocations,
                linkedProps = linkedProps
            });
        }

        // 3. НОТАТКИ ДО СЦЕНИ (Права панель)
        [HttpPut("scene/{sceneId}/notes")]
        public async Task<IActionResult> UpdateNotes(int sceneId, [FromBody] string notes)
        {
            if (notes != null && notes.Length > 2000)
            {
                return BadRequest(new { message = "Notes cannot exceed 2000 characters." });
            }

            var scene = await _context.Scenes.FindAsync(sceneId);
            if (scene == null) return NotFound();

            scene.Notes = notes; // Зберігає всі \n та пробіли
            await _context.SaveChangesAsync();
            return NoContent();
        }

        [HttpPut("project/{projectId}/scenes/reorder")]
        public async Task<IActionResult> ReorderScenes(int projectId, [FromBody] List<int> orderedSceneIds)
        {
            if (orderedSceneIds == null || !orderedSceneIds.Any()) return Ok();

            // Викликаємо збережену процедуру для безпечного транзакційного сортування
            await _context.Database.ExecuteSqlRawAsync(
                "CALL sp_reorder_scenes({0}, {1})",
                projectId,
                orderedSceneIds.ToArray()
            );

            return Ok();
        }


        // СТВОРЕННЯ НОВОЇ СЦЕНИ
        [HttpPost("project/{projectId}/scene")]
        public async Task<IActionResult> CreateScene(int projectId)
        {
            // Знаходимо максимальний SequenceNum у цьому проекті
            var maxSeq = await _context.Scenes
                .Where(s => s.ProjectId == projectId)
                .MaxAsync(s => (int?)s.SequenceNum) ?? 0;

            var newScene = new Scene
            {
                ProjectId = projectId,
                SequenceNum = maxSeq + 1,
                SluglineText = "NEW SCENE",
                EstimatedDuration = TimeSpan.Zero
            };

            _context.Scenes.Add(newScene);
            await _context.SaveChangesAsync();

            return Ok(new
            {
                id = newScene.Id,
                sequenceNum = newScene.SequenceNum,
                sluglineText = newScene.SluglineText
            });
        }

        // ДОДАЙТЕ В ScriptController.cs
        [HttpDelete("scene/{sceneId}")]
        public async Task<IActionResult> DeleteScene(int sceneId)
        {
            var scene = await _context.Scenes.FindAsync(sceneId);
            if (scene == null) return NotFound();

            int projectId = scene.ProjectId;
            int deletedSeqNum = scene.SequenceNum;

            // Видаляємо сцену (ScriptElements видаляться автоматично, якщо налаштовано Cascade Delete)
            _context.Scenes.Remove(scene);
            await _context.SaveChangesAsync();

            // Перераховуємо номери для сцен, що йшли ПІСЛЯ видаленої
            var trailingScenes = await _context.Scenes
                .Where(s => s.ProjectId == projectId && s.SequenceNum > deletedSeqNum)
                .OrderBy(s => s.SequenceNum)
                .ToListAsync();

            foreach (var s in trailingScenes)
            {
                s.SequenceNum--;
            }

            await _context.SaveChangesAsync();

            return Ok(new { message = "Scene deleted and sequence updated" });
        }

        // --------------------------------------------------------
        // НОВІ ЕНДПОІНТИ ДЛЯ ПРАВОЇ ПАНЕЛІ (РЕСУРСИ)
        // --------------------------------------------------------

        // Отримання всіх доступних ресурсів проекту для модалок
        [HttpGet("project/{projectId}/resources")]
        public async Task<IActionResult> GetProjectResources(int projectId)
        {
            var roles = await _context.Roles.Where(r => r.ProjectId == projectId)
                .Select(r => new { id = r.Id, name = r.RoleName, color = r.ColorHex, isAutoGenerated = r.IsAutoGenerated }).ToListAsync();

            var locations = await _context.Resources.Include(r => r.Location).Where(r => r.ProjectId == projectId && r.Location != null)
                .Select(r => new { id = r.Id, name = r.Location.LocationName, type = r.Location.LocationType }).ToListAsync();

            var props = await _context.Resources.Include(r => r.Prop).Where(r => r.ProjectId == projectId && r.Prop != null)
                .Select(r => new { id = r.Id, name = r.Prop.PropName }).ToListAsync();

            return Ok(new { roles, locations, props });
        }

        // Прикріплення існуючого ресурсу до сцени
        [HttpPost("scene/{sceneId}/resource/{resourceId}")]
        public async Task<IActionResult> LinkResource(int sceneId, int resourceId)
        {
            if (!await _context.SceneResources.AnyAsync(sr => sr.SceneId == sceneId && sr.ResourceId == resourceId))
            {
                _context.SceneResources.Add(new SceneResource { SceneId = sceneId, ResourceId = resourceId });
                await _context.SaveChangesAsync();
            }
            return Ok();
        }

        // Відкріплення ресурсу від сцени
        [HttpDelete("scene/{sceneId}/resource/{resourceId}")]
        public async Task<IActionResult> UnlinkResource(int sceneId, int resourceId)
        {
            var sr = await _context.SceneResources.FirstOrDefaultAsync(x => x.SceneId == sceneId && x.ResourceId == resourceId);
            if (sr != null)
            {
                _context.SceneResources.Remove(sr);
                await _context.SaveChangesAsync();
            }
            return Ok();
        }

        // Зміна кольору персонажа
        [HttpPut("role/{roleId}/color")]
        public async Task<IActionResult> UpdateRoleColor(int roleId, [FromBody] string color)
        {
            var role = await _context.Roles.FindAsync(roleId);
            if (role == null) return NotFound();

            role.ColorHex = color;
            role.IsAutoGenerated = false; // Тільки-но ми змінили колір, він перестає бути "Auto"
            await _context.SaveChangesAsync();
            return Ok();
        }

        // Швидке створення Ролі
        public class QuickResourceDto
        {
            [Required]
            [MaxLength(150, ErrorMessage = "Name is too long. Max 150 characters allowed.")]
            public string Name { get; set; } = null!;
        }

        [HttpPost("project/{projectId}/role")]
        public async Task<IActionResult> QuickCreateRole(int projectId, [FromBody] QuickResourceDto dto)
        {
            if (string.IsNullOrWhiteSpace(dto.Name)) return BadRequest(new { message = "Role name cannot be empty." });

            var existingRole = await _context.Roles
                .FirstOrDefaultAsync(r => r.ProjectId == projectId && r.RoleName.ToLower() == dto.Name.ToLower());

            if (existingRole != null)
            {
                return Ok(new { id = existingRole.Id, name = existingRole.RoleName, color = existingRole.ColorHex });
            }

            var res = new Resource { ProjectId = projectId };
            _context.Resources.Add(res);
            await _context.SaveChangesAsync();

            var role = new Role { Id = res.Id, ProjectId = projectId, RoleName = dto.Name.Trim(), ColorHex = "#3AB9A0", IsAutoGenerated = false };
            _context.Roles.Add(role);
            await _context.SaveChangesAsync();

            return Ok(new { id = role.Id, name = role.RoleName, color = role.ColorHex });
        }

        // Швидке створення або отримання Локації
        [HttpPost("project/{projectId}/location")]
        public async Task<IActionResult> QuickCreateLocation(int projectId, [FromBody] QuickResourceDto dto)
        {
            if (string.IsNullOrWhiteSpace(dto.Name)) return BadRequest(new { message = "Location name cannot be empty." });

            var existingLoc = await _context.Locations
                .Include(l => l.IdNavigation)
                .FirstOrDefaultAsync(l => l.LocationName.ToLower() == dto.Name.ToLower());

            if (existingLoc != null)
            {
                if (existingLoc.IdNavigation.ProjectId == projectId)
                    return Ok(new { id = existingLoc.Id, name = existingLoc.LocationName, type = existingLoc.LocationType });
                else
                    return BadRequest(new { message = $"Location '{dto.Name}' already exists in another project. Please use a different name." });
            }

            var res = new Resource { ProjectId = projectId };
            _context.Resources.Add(res);
            await _context.SaveChangesAsync();

            var loc = new Location { Id = res.Id, LocationName = dto.Name.Trim(), LocationType = "interior" };
            _context.Locations.Add(loc);
            await _context.SaveChangesAsync();

            return Ok(new { id = loc.Id, name = loc.LocationName, type = loc.LocationType });
        }

        // Швидке створення або отримання Реквізиту
        [HttpPost("project/{projectId}/prop")]
        public async Task<IActionResult> QuickCreateProp(int projectId, [FromBody] QuickResourceDto dto)
        {
            if (string.IsNullOrWhiteSpace(dto.Name)) return BadRequest(new { message = "Prop name cannot be empty." });

            var existingProp = await _context.Props
                .Include(p => p.IdNavigation)
                .FirstOrDefaultAsync(p => p.PropName.ToLower() == dto.Name.ToLower());

            if (existingProp != null)
            {
                if (existingProp.IdNavigation.ProjectId == projectId)
                    return Ok(new { id = existingProp.Id, name = existingProp.PropName });
                else
                    return BadRequest(new { message = $"Prop '{dto.Name}' already exists in another project. Please use a different name." });
            }

            var res = new Resource { ProjectId = projectId };
            _context.Resources.Add(res);
            await _context.SaveChangesAsync();

            var prop = new Prop { Id = res.Id, PropName = dto.Name.Trim(), PropType = "action", PropStatus = "available", AcquisitionType = "buy" };
            _context.Props.Add(prop);
            await _context.SaveChangesAsync();

            return Ok(new { id = prop.Id, name = prop.PropName });
        }

        // --------------------------------------------------------
        // АЛГОРИТМ РОЗРАХУНКУ ТРИВАЛОСТІ СЦЕНИ
        // Базується на стандарті кіноіндустрії: ~1 хвилина на сторінку сценарію.
        // Стандартна сторінка = ~55 слів діалогу або ~200 символів action-тексту.
        // Кожен тип блоку має власний "ваговий коефіцієнт".
        // --------------------------------------------------------
        private static TimeSpan EstimateSceneDuration(List<ScriptBlockDto> blocks)
        {
            double totalSeconds = 0;

            foreach (var block in blocks)
            {
                string type = block.Type.ToLower();
                string content = block.Content?.Trim() ?? "";
                if (content.Length == 0) continue;

                int wordCount = content.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length;

                switch (type)
                {
                    // ДІАЛОГ: читається зі швидкістю ~120 слів/хв (природна мова актора)
                    case "dialogue":
                        totalSeconds += (wordCount / 120.0) * 60;
                        break;

                    // РЕМАРКА (parenthetical): коротка пауза + час читання
                    case "parenthetical":
                        totalSeconds += 1.5 + (wordCount / 150.0) * 60;
                        break;

                    // ПЕРСОНАЖ (character): пауза перед репліками ~0.8с
                    case "character":
                        totalSeconds += 0.8;
                        break;

                    // ACTION: описи дій знімають час на екрані.
                    // Стандарт: ~1 хвилина на 55 слів (1 стор. = ~55 слів action = 1 хв)
                    case "action":
                        totalSeconds += (wordCount / 55.0) * 60;
                        break;

                    // TRANSITION (FADE OUT, CUT TO тощо): суто технічний, ~1.5с
                    case "transition":
                        totalSeconds += 1.5;
                        break;

                    // SHOT (INSERT, CLOSE ON тощо): короткий кадр, ~2–3с залежно від довжини
                    case "shot":
                        totalSeconds += 2.0 + (wordCount / 80.0) * 60;
                        break;

                    // SCENE_HEADING: не впливає на хронометраж
                    case "scene_heading":
                    default:
                        break;
                }
            }

            // Мінімум 3 секунди для непустої сцени, максимум 30 хвилин (захист від аномалій)
            totalSeconds = Math.Clamp(totalSeconds, blocks.Any(b => b.Type.ToLower() != "scene_heading") ? 3 : 0, 1800);

            return TimeSpan.FromSeconds(Math.Round(totalSeconds));
        }

        [HttpPost("scene/{sceneId}/merge-into-previous")]
        public async Task<IActionResult> MergeIntoPrevious(int sceneId)
        {
            var scene = await _context.Scenes
                .Include(s => s.ScriptElements)
                .Include(s => s.SceneResources)
                .FirstOrDefaultAsync(s => s.Id == sceneId);

            if (scene == null) return NotFound();

            var prevScene = await _context.Scenes
                .Include(s => s.ScriptElements)
                .Include(s => s.SceneResources)
                .FirstOrDefaultAsync(s => s.ProjectId == scene.ProjectId
                                       && s.SequenceNum == scene.SequenceNum - 1);

            if (prevScene == null)
                return BadRequest(new { message = "Cannot merge: this is the first scene." });

            // Крок 1: переносимо ScriptElements
            int maxOrder = prevScene.ScriptElements.Any()
                ? prevScene.ScriptElements.Max(e => e.OrderIndex)
                : -1;

            foreach (var el in scene.ScriptElements.OrderBy(e => e.OrderIndex))
            {
                el.SceneId = prevScene.Id;
                el.OrderIndex = ++maxOrder;
            }

            // Крок 2: переносимо SceneResources (без дублів)
            foreach (var sr in scene.SceneResources.ToList())
            {
                bool alreadyLinked = prevScene.SceneResources.Any(x => x.ResourceId == sr.ResourceId);
                if (!alreadyLinked)
                {
                    _context.SceneResources.Add(new SceneResource
                    {
                        SceneId = prevScene.Id,
                        ResourceId = sr.ResourceId
                    });
                }
                _context.SceneResources.Remove(sr);
            }

            // ✅ Зберігаємо переміщення ДО видалення — інакше EF скасує зміни
            await _context.SaveChangesAsync();

            // Крок 3: видаляємо порожню сцену
            int deletedSeqNum = scene.SequenceNum;
            int projectId = scene.ProjectId;
            _context.Scenes.Remove(scene);
            await _context.SaveChangesAsync();

            // Крок 4: перенумеровуємо сцени після видаленої
            var trailingScenes = await _context.Scenes
                .Where(s => s.ProjectId == projectId && s.SequenceNum > deletedSeqNum)
                .OrderBy(s => s.SequenceNum)
                .ToListAsync();

            foreach (var s in trailingScenes)
            {
                s.SequenceNum--;
            }
            await _context.SaveChangesAsync();

            return Ok(new { mergedIntoSceneId = prevScene.Id });
        }
    }
}