using CineCoreBack.DTOs;
using CineCoreBack.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CineCoreBack.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ScriptController : ControllerBase
    {
        private readonly DbConfig _context;

        public ScriptController(DbConfig context)
        {
            _context = context;
        }

        // 1. АВТОМАТИЧНЕ ЗБЕРЕЖЕННЯ ТА СИНХРОНІЗАЦІЯ
        [HttpPost("scene/{sceneId}/autosave")]
        public async Task<IActionResult> AutoSaveScript(int sceneId, [FromBody] ScriptSaveDto dto)
        {
            var scene = await _context.Scenes.FindAsync(sceneId);
            if (scene == null) return NotFound();

            // КРОК А: Робота з персонажами
            var existingRoles = await _context.Roles
                .Where(r => r.ProjectId == dto.ProjectId)
                .ToListAsync();

            var characterBlocks = dto.Blocks
                .Where(b => b.Type.ToLower() == "character")
                .Select(b => b.Content.Trim().ToUpper())
                .Distinct()
                .ToList();

            foreach (var name in characterBlocks)
            {
                if (!existingRoles.Any(r => r.RoleName.ToUpper() == name))
                {
                    // Створюємо новий Resource + Role
                    var res = new Resource { ProjectId = dto.ProjectId };
                    _context.Resources.Add(res);
                    await _context.SaveChangesAsync();

                    var newRole = new Role
                    {
                        Id = res.Id,
                        ProjectId = dto.ProjectId,
                        RoleName = name,
                        IsAutoGenerated = true,
                        ColorHex = "#3AB9A0"
                    };
                    _context.Roles.Add(newRole);
                    existingRoles.Add(newRole);
                }
            }
            await _context.SaveChangesAsync();

            // КРОК Б: Wipe & Replace (Очищення старих елементів сцени)
            var oldElements = _context.ScriptElements.Where(e => e.SceneId == sceneId);
            _context.ScriptElements.RemoveRange(oldElements);

            // КРОК В: Запис нових блоків
            int order = 0;
            int? currentRoleId = null;

            foreach (var block in dto.Blocks)
            {
                string type = block.Type.ToLower();

                // Якщо це заголовок - оновлюємо саму сцену і не пишемо в Elements
                if (type == "scene_heading")
                {
                    scene.SluglineText = block.Content;
                    continue;
                }

                // Логіка прив'язки реплік до персонажа
                if (type == "character")
                {
                    currentRoleId = existingRoles.FirstOrDefault(r => r.RoleName.ToUpper() == block.Content.Trim().ToUpper())?.Id;
                }
                else if (type != "dialogue" && type != "parenthetical")
                {
                    currentRoleId = null;
                }

                _context.ScriptElements.Add(new ScriptElement
                {
                    SceneId = sceneId,
                    OrderIndex = order++,
                    Content = block.Content,
                    ElementType = type,
                    RoleId = currentRoleId
                });
            }

            await _context.SaveChangesAsync();

            // КРОК Г: Ghost Buster (Видаляємо авто-ролі без жодного елемента в проекті)
            var ghostRoles = await _context.Roles
                .Include(r => r.ScriptElements)
                .Where(r => r.ProjectId == dto.ProjectId && r.IsAutoGenerated && !r.ScriptElements.Any())
                .ToListAsync();

            if (ghostRoles.Any())
            {
                var ids = ghostRoles.Select(r => r.Id).ToList();
                _context.Roles.RemoveRange(ghostRoles);
                _context.Resources.RemoveRange(_context.Resources.Where(r => ids.Contains(r.Id)));
                await _context.SaveChangesAsync();
            }

            return Ok(new { message = "Synced" });
        }

        // 1. ОТРИМАННЯ СПИСКУ СЦЕН (ДЛЯ ЛІВОЇ ПАНЕЛІ)
        [HttpGet("project/{projectId}/scenes")]
        public async Task<IActionResult> GetProjectScenes(int projectId)
        {
            var scenes = await _context.Scenes
                .Where(s => s.ProjectId == projectId)
                .OrderBy(s => s.SequenceNum)
                .Select(s => new {
                    id = s.Id,
                    sequenceNum = s.SequenceNum,
                    sluglineText = s.SluglineText,
                    estimatedDuration = s.EstimatedDuration
                })
                .ToListAsync();
            return Ok(scenes);
        }

        // 2. ОТРИМАННЯ СКРИПТУ + НОТАТОК (ДЛЯ ЦЕНТРАЛЬНОЇ ТА ПРАВОЇ ПАНЕЛЕЙ)
        [HttpGet("scene/{sceneId}")]
        public async Task<IActionResult> GetScript(int sceneId)
        {
            var scene = await _context.Scenes
                .Include(s => s.ScriptElements)
                    .ThenInclude(e => e.Role)
                .FirstOrDefaultAsync(s => s.Id == sceneId);

            if (scene == null) return NotFound();

            var blocks = new List<object> {
                new { id = "h-" + scene.Id, type = "scene_heading", content = scene.SluglineText }
            };

            var elements = scene.ScriptElements.OrderBy(e => e.OrderIndex).Select(e => new {
                id = e.Id.ToString(),
                type = e.ElementType,
                content = e.Content,
                charId = e.RoleId?.ToString(),
                color = e.Role?.ColorHex ?? "#444"
            });

            blocks.AddRange(elements);

            // ПОВЕРТАЄМО ОБ'ЄКТ (Блоки + Нотатки)
            return Ok(new
            {
                notes = scene.Notes,
                blocks = blocks
            });
        }

        // 3. НОТАТКИ ДО СЦЕНИ (Права панель)
        [HttpPut("scene/{sceneId}/notes")]
        public async Task<IActionResult> UpdateNotes(int sceneId, [FromBody] string notes)
        {
            var scene = await _context.Scenes.FindAsync(sceneId);
            if (scene == null) return NotFound();

            scene.Notes = notes; // Зберігає всі \n та пробіли
            await _context.SaveChangesAsync();
            return NoContent();
        }

        // 4. ПЕРЕВПОРЯДКУВАННЯ СЦЕН (DRAG & DROP)
        [HttpPut("project/{projectId}/scenes/reorder")]
        public async Task<IActionResult> ReorderScenes(int projectId, [FromBody] List<int> orderedSceneIds)
        {
            var scenes = await _context.Scenes.Where(s => s.ProjectId == projectId).ToListAsync();

            for (int i = 0; i < orderedSceneIds.Count; i++)
            {
                var scene = scenes.FirstOrDefault(s => s.Id == orderedSceneIds[i]);
                if (scene != null)
                {
                    scene.SequenceNum = i + 1; // Нумерація з 1
                }
            }

            await _context.SaveChangesAsync();
            return Ok();
        }

        // СТВОРЕННЯ НОВОЇ СЦЕНИ
        [HttpPost("project/{projectId}/scene")]
        public async Task<IActionResult> CreateScene(int projectId)
        {
            // Знаходимо максимальний SequenceNum у цьому проекті
            var maxSeq = await _context.Scenes
                .Where(s => s.ProjectId == projectId)
                .MaxAsync(s => (int?)s.SequenceNum) ?? 0;

            var newScene = new Scene
            {
                ProjectId = projectId,
                SequenceNum = maxSeq + 1,
                SluglineText = "NEW SCENE",
                EstimatedDuration = TimeSpan.Zero
            };

            _context.Scenes.Add(newScene);
            await _context.SaveChangesAsync();

            return Ok(new
            {
                id = newScene.Id,
                sequenceNum = newScene.SequenceNum,
                sluglineText = newScene.SluglineText
            });
        }
    }
}